# Generated by Django 4.2.6 on 2023-12-27 04:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('prod_brand', models.CharField(max_length=50)),
                ('prod_name', models.CharField(max_length=50)),
                ('prod_desc', models.CharField(max_length=255)),
                ('prod_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('prod_pack_size', models.CharField(max_length=10)),
                ('prod_status', models.CharField(default='Upcoming', max_length=15)),
                ('cat_id', models.ForeignKey(db_column='cat_id', on_delete=django.db.models.deletion.CASCADE, to='base.category')),
            ],
            options={
                'db_table': 'product',
                'unique_together': {('prod_brand', 'prod_name', 'prod_pack_size')},
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('prod_id', models.OneToOneField(db_column='prod_id', editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.product')),
                ('inv_qoh', models.IntegerField()),
                ('inv_status', models.CharField(default='In Stock', max_length=15)),
                ('inv_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('emp_fname', models.CharField(max_length=50)),
                ('emp_lname', models.CharField(max_length=50)),
                ('emp_gender', models.CharField(max_length=6)),
                ('emp_mobile', models.CharField(max_length=11)),
                ('emp_dob', models.DateField()),
                ('emp_address', models.CharField(max_length=255)),
                ('emp_email', models.EmailField(max_length=254, unique=True)),
                ('emp_password', models.CharField(max_length=20)),
                ('emp_image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('emp_created_at', models.DateField(auto_now_add=True)),
                ('emp_updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'employee',
                'unique_together': {('emp_fname', 'emp_lname', 'emp_dob')},
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('emp_access', models.BooleanField(default=False)),
                ('emp', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
