# Generated by Django 4.2.6 on 2023-12-31 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('req_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('req_edd', models.DateField(null=True)),
                ('req_status', models.CharField(max_length=10)),
                ('req_comments', models.CharField(max_length=255)),
                ('req_received_date', models.DateTimeField(blank=True, null=True)),
                ('req_approved_date', models.DateTimeField(blank=True, null=True)),
                ('req_created_at', models.DateTimeField(auto_now_add=True)),
                ('emp_id', models.ForeignKey(db_column='emp_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
            options={
                'db_table': 'requisition',
            },
        ),
        migrations.CreateModel(
            name='RequisitionItem',
            fields=[
                ('req_item_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('req_qty', models.IntegerField()),
                ('req_item_received_qty', models.IntegerField(null=True)),
                ('req_for_purchase', models.BooleanField(default=False)),
                ('prod_id', models.ForeignKey(db_column='prod_id', on_delete=django.db.models.deletion.CASCADE, to='base.product')),
                ('req_id', models.ForeignKey(db_column='req_id', on_delete=django.db.models.deletion.CASCADE, to='base.requisition')),
            ],
            options={
                'db_table': 'requisition_item',
                'unique_together': {('req_id', 'prod_id')},
            },
        ),
    ]
