# Generated by Django 4.2.6 on 2024-01-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_supplier_contact_supplier_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='cont_per_fb_acc',
            field=models.URLField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sup_fb_acc',
            field=models.URLField(max_length=150, unique=True),
        ),
    ]
