# Generated by Django 4.2.6 on 2024-01-02 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_contact_cont_per_status_supplier_sup_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_Order',
            fields=[
                ('po_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('po_edd', models.DateField(null=True)),
                ('po_status', models.CharField(default='PENDING', max_length=10)),
                ('po_received_date', models.DateTimeField(blank=True, null=True)),
                ('po_created_at', models.DateTimeField(auto_now_add=True)),
                ('sup_id', models.ForeignKey(db_column='sup_id', on_delete=django.db.models.deletion.CASCADE, to='base.supplier')),
            ],
            options={
                'db_table': 'purchase_order',
            },
        ),
        migrations.CreateModel(
            name='Purchase_Order_Item',
            fields=[
                ('po_item_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('po_item_qty', models.IntegerField()),
                ('po_item_received_qty', models.IntegerField(default=0, null=True)),
                ('po_item_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('po_item_total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('po_item_status', models.CharField(default='PENDING', max_length=10)),
                ('po_id', models.ForeignKey(db_column='po_id', on_delete=django.db.models.deletion.CASCADE, to='base.purchase_order')),
                ('prod_id', models.ForeignKey(db_column='prod_id', on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
            options={
                'db_table': 'purchase_order_item',
                'unique_together': {('po_id', 'prod_id')},
            },
        ),
    ]
