# Generated by Django 4.2.6 on 2024-01-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_purchase_order_purchase_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_status',
            field=models.BooleanField(default=True),
        ),
    ]
