# Generated by Django 4.2.6 on 2024-01-04 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_employee_emp_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('cont_per_fname', 'cont_per_lname')},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='cont_per_mname',
        ),
    ]
