# Generated by Django 5.0 on 2024-01-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_supplier_sup_loc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='sup_mname',
        ),
        migrations.AlterField(
            model_name='contact',
            name='cont_per_email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cont_per_fb_acc',
            field=models.URLField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cont_per_fname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cont_per_lname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cont_per_status',
            field=models.CharField(default='Active', max_length=30),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='po_status',
            field=models.CharField(default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='purchase_order_item',
            name='po_item_status',
            field=models.CharField(default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sup_company',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sup_email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sup_fb_acc',
            field=models.URLField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sup_fname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sup_lname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sup_loc',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sup_status',
            field=models.CharField(default='Active', max_length=30),
        ),
    ]
