# Generated by Django 5.0 on 2024-01-06 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_supplier_sup_mname_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('sup_fname', 'sup_lname')},
        ),
    ]
