# Generated by Django 4.2.6 on 2024-01-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_supplier_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='inv_reorder',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
