from django.urls import path
from django.conf import settings  
from django.conf.urls.static import static 
from . import views

urlpatterns = [
    path('', views.home),
    path('home', views.home, name='home'),
    path('products/list', views.product_list, name='products'),
    path('products/add', views.add_product, name='add_product'),
    path('products/create_product', views.view_form_product, name='view_form_product'),
    path('products/edit_product/<prod_id>', views.edit_product, name='edit_product'),
    path('products/delete_product/<prod_id>', views.delete_product, name='delete_product'),
    path('products/category', views.category_view, name='category_view'),
    path('products/category/add', views.category_add, name='category_add'),
    path('products/delete_category/<cat_id>', views.delete_category, name='delete_category'),
    path('products/inventory/<str:inv_status>', views.inventory, name='inventory'),
    path('products/inventory/add/stock', views.add_inventory, name='add_stock'),
    path('products/search', views.search_product, name='search_product'),
    path('products/<prod_id>/details', views.product_details, name='product_details'),
    path('employee/add', views.register_acc, name='register_acc'),
    path('employee/register', views.register, name='register'),
    path('user_login', views.user_login, name='user_login'),
    path('employee/logout', views.logout_emp, name='logout_emp'),
    path('employee/<int:emp_id>/edit', views.edit_employee, name='edit_employee'),
    path('edit_profile', views.edit_profile, name='edit_profile'),
    path('save_profile_changes', views.save_profile_changes, name='save_profile_changes'),
    path('change_password', views.change_password, name='change_password'),
    path('employee/inactive/', views.retrieve_view, name='retrieve_employee'),
    path('employee/list', views.viewaccount, name='viewaccount'),
    path('employee/<int:emp_id>/update', views.update, name='update_employee'),
    path('employee/<int:emp_id>/delete',views.delete, name ='delete_employee'),
    path('employee_details/<int:emp_id>/', views.employee_details, name='employee_details'),
    path('employee_details/<int:emp_id>/retrieve', views.retrieve_emp, name='retrieve'),
    path('requisition/create', views.requisition, name='requisition'),
    path('employee/requisition/<str:req_status>/', views.emp_requisition, name='emp_requisition'),
    path('<str:req_status>/requisition/<str:req_id>/delete', views.delete_requisition, name='delete_requisition'),
    path('employee/requisition/<int:req_id>/items', views.view_request_items, name='view_request_items'),
    path('add_req', views.add_req, name='add_req'),
    path('requisition/<str:req_status>/', views.admin_requisition_view, name='admin_requisition'),
    path('requisition/<int:req_id>/items', views.view_pending_request_items, name='pending_request_items'),
    path('requisition/approval', views.requisition_approval, name='requisition_approval'),
    path('requisition/approve', views.requisition_approval, name='approve_requisition'),
    path('requisition/received', views.mark_received, name='mark_received'),
    path('supplier/list', views.supplier_list, name='supplier_list'),
    path('supplier/create', views.add_sup, name='add_supplier'),
    path('supplier/<int:sup_id>/delete', views.delete_sup, name='delete_supplier'),
    path('supplier/<int:sup_id>/<int:prod_id>/delete', views.delete_supplier_item, name='delete_supplier_item'),
    path('supplier/<int:sup_id>/edit', views.edit_supplier, name='edit_supplier'),
    path('supplier/<int:sup_id>/update', views.update_supplier, name='update_supplier'),
    path('supplier/<int:sup_id>/contact/create', views.add_contact, name='add_contact'),
    path('supplier/<int:sup_id>/details', views.sup_details, name='supplier_details'),
    path('supplier/item', views.add_sup_item, name='add_supplier_item'),
    path('purchase/order/<str:po_status>/', views.po_list, name='purchase_order'),
    path('purchase/order/add', views.add_po, name='add_po'),
    path('purchase/order/create', views.view_po, name='view_po'),
    path('purchase/order/<int:po_id>/cancel', views.cancel_po, name='cancel_po'),
    path('purchase/order/<int:po_id>/items', views.view_po_items, name='view_po_items'),
    path('purchase/order/complete', views.confirm_po, name='confirm_po'),
    path('purchase/order/<str:po_status>/<int:po_id>/delete', views.delete_po, name='delete_po'),
    path('supplier/search', views.search_supplier, name='search_supplier'),
    path('supplier/contact/<int:cont_id>/deact', views.deact_contact, name='delete_contact'),
    path('supplier/id=<int:sup_id>/contact/change', views.change_contact, name='change_contact'),
    path('supplier/id=<int:sup_id>/activate', views.activate_supplier, name='reactivate'),
    path('supplier/contact/<int:cont_id>/activate', views.activate_contact, name='activate_contact'),
    path('purchase/order/urgent', views.urgent_req_view, name='urgent'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)